### PR TITLE
Delete v0 and deprecated methods

### PR DESCRIPTION
**Pull request by napstr**
The dream.

The day where this branch can be merged is still a good while away.
The work left are mostly implementing v1 endpoints in the main FredBoat project.

### CODE REVIEW

**Comment by SuhanKoh** [comment]
imo, we could merge this, and use tagging for existing v0

**Comment by napstr** [comment]
We could do a stable release from the current branch state and then pull this into dev.

**Comment by napstr** [comment]
Pulling this will cause the selfhosters to have a good time :tm:
I'll see that get a 24h notice.

**Comment by SuhanKoh** [comment]
Just thinking, we could have a branch dedicated for v0, and announce no new feature will be implemented on v0 moving forward (hotfix will be done on this branch), until v1 hit prod.

**Comment by Frederikam** [comment]
@napstr if this PR is still ready, we can pull this at the same time as https://github.com/Frederikam/FredBoat/pull/531

**Comment by napstr** [comment]
It is ready but v0 endpoints are still used. No need to complicate things unnecessarily imo.

**Comment by napstr** [comment]
Quarterdeck has been deprecated afaik

**Pull request closed without merging**
