### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by napstr**

### CODE REVIEW

**Comment by Frederikam** [comment]
Are you confident that this doesn't break? This changes a lot of things I am not familiar with.

**Comment by napstr** [comment]
Which things do you mean? 
- gradle changes are fine otherwise the build would be broken^^
- sonar changes same (actually I need you to approve the sonar github app for this project)
- code changes are due to deprecations so that should be fine
- tests had some changes due to compiler errors but are green now so I don't see a risk there

I did some local tests via curl and things were fine but before deploying I was planning to do an additional dry-run against a copy of the existing db just to make sure Flyway & Hibernate still work.

**Comment by Frederikam** [comment]
I always get nervous when updating dependencies

**Comment by napstr** [comment]
> if it hurts, do it more often

:)

**Pull request merged**
